package com.job.entity;

// Generated Mar 27, 2013 11:14:43 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplyJob generated by hbm2java
 */
@Entity
@Table(name = "apply_job", catalog = "mydb")
public class ApplyJob implements java.io.Serializable {

	private static final long serialVersionUID = -189326194772551831L;
	private Integer aplicationId;
	private User user;
	private String name;
	private String email;
	private String message;
	private byte[] uploadCv;
	private byte[] uploadCover;

	public ApplyJob() {
	}

	public ApplyJob(User user, String name, String email, String message,
			byte[] uploadCv) {
		this.user = user;
		this.name = name;
		this.email = email;
		this.message = message;
		this.uploadCv = uploadCv;
	}

	public ApplyJob(User user, String name, String email, String message,
			byte[] uploadCv, byte[] uploadCover) {
		this.user = user;
		this.name = name;
		this.email = email;
		this.message = message;
		this.uploadCv = uploadCv;
		this.uploadCover = uploadCover;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "aplication_id", unique = true, nullable = false)
	public Integer getAplicationId() {
		return this.aplicationId;
	}

	public void setAplicationId(Integer aplicationId) {
		this.aplicationId = aplicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "upload_cv", nullable = false)
	public byte[] getUploadCv() {
		return this.uploadCv;
	}

	public void setUploadCv(byte[] uploadCv) {
		this.uploadCv = uploadCv;
	}

	@Column(name = "upload_cover")
	public byte[] getUploadCover() {
		return this.uploadCover;
	}

	public void setUploadCover(byte[] uploadCover) {
		this.uploadCover = uploadCover;
	}

}
