package com.job.entity;

// Generated Mar 27, 2013 11:14:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "JobBoard")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 5616660330372063190L;
	private Integer userId;
	private String username;
	private String email;
	private String password;
	private EditCompProfile editCompProfile;
	private Set<NewJobDescription> newJobDescriptions = new HashSet<NewJobDescription>(0);
	private Set<ApplyJob> applyJobs = new HashSet<ApplyJob>(0);

	public User() {
	}

	public User(String username, String email, String password) {
		this.username = username;
		this.email = email;
		this.password = password;
	}

	public User(String username, String email, String password,
			EditCompProfile editCompProfile,
			Set<NewJobDescription> newJobDescriptions, Set<ApplyJob> applyJobs) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.editCompProfile = editCompProfile;
		this.newJobDescriptions = newJobDescriptions;
		this.applyJobs = applyJobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public EditCompProfile getEditCompProfile() {
		return this.editCompProfile;
	}

	public void setEditCompProfile(EditCompProfile editCompProfile) {
		this.editCompProfile = editCompProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<NewJobDescription> getNewJobDescriptions() {
		return this.newJobDescriptions;
	}

	public void setNewJobDescriptions(Set<NewJobDescription> newJobDescriptions) {
		this.newJobDescriptions = newJobDescriptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ApplyJob> getApplyJobs() {
		return this.applyJobs;
	}

	public void setApplyJobs(Set<ApplyJob> applyJobs) {
		this.applyJobs = applyJobs;
	}

}
